### PR TITLE
Updates to data to work better with import script

### PR DESCRIPTION
**Pull request by symposion**
So after all the various issues with the spells and monster json formats, I figured it would be better to update the format to be closer to what is actually sent into the sheet + stick a version number on it so I can check that people are using the right version.

### CODE REVIEW

**Comment by mlenser** [comment]
Issues:
- Can we use semantic versioning?
- Spaces before every trait's text
- Spaces after trait names
- resistances is listed as "Damage Resistances" on the actual monsters so the damage part should stay
- same with immunities
- Spells is the name I use on the sheet, not sure why it should be spellBook

The rest that I can see looks ok, but I can't see it all on Github

**Comment by symposion** [comment]
Semver: sure, will change
Spaces: sorry, will reformat 
Immunities/Resistances: this comes from the Compendium JSON format. Since I was changing the format I thought It made most sense to match it with the Compendium. it can't be exactly the same as the sheet, since the sheet uses underscores instead of camelCase. It doesn't particularly bother me one way or the other but I thought that we might as well end up with something that's as close to the Compendium JSON as practical
spellBook: again, this is based on the Compendium JSON

If you'd rather keep the old names in these cases could you just reconfirm and I'll change them back again. Thanks.

**Comment by mlenser** [comment]
Ah, makes sense. Let me check again in the morning

**Comment by symposion** [comment]
Have pushed the other changes requested. Will wait to hear from you on the property naming.

**Comment by mlenser** [comment]
So I looked it over again and I think we should break from roll20 in regards to immunities/resistances. Primarily because "immunities" is vague as there are condition immunities and damage immunities. So I would choose to leave it as it was (or something similar where the types can be differentiated without having both in the same character).

I'd, personally, say to keep spellbook as "spells" as well as that is how monsters define it (very few would actually have books).

Let me know your thoughts.

**Comment by symposion** [comment]
I'm not that fussed one way or the other, but on balance I think you're right. I'll change this everywhere to match what we've agreed and then we can finally draw a line under this!

**Comment by mlenser** [comment]
sounds good

**Comment by symposion** [comment]
Ok, those properties are back how they were now.

**Comment by mlenser** [comment]
Sorry, 1 last thing!

Can we remove empty senses? I can do it on my end too.

**Comment by symposion** [comment]
Yep, and I've realised that I've managed to back out a whole bunch of my property name fixes to the spells as well :-(  Really I should just leave all this until next week rather than trying to fit it into 5 minute windows here and there but I can't help myself - I hate leaving things partially finished....

**Comment by symposion** [comment]
Right, hopefully that's everything now... let me know if there's anything else that needs changing

**Comment by symposion** [comment]
Erk, haven't recompiled it though - if you merge could you rebuild the dist afterwards?

**Comment by mlenser** [comment]
compiled

**Pull request merged**
