### PR TITLE
Remove extra damage at higher lvls for Eldritch Blast.

### PR DESCRIPTION
**Pull request by alienth**
Higher levels result in more beams, each with a separate attack roll.
The damage for all of the beams should be rolled only once (PHB 196).

The behaviour from the script resulted in additional damage die being rolled on a single attack, without multiple attack rolls. This is problematic as each beam isn't guaranteed to hit. Additionally, damage bonuses need to be applied to each beam.

As the Shaped charsheet doesn't support multiple attack rolls for a spell, the current way to get the correct behaviour would be to have the player cast the spell once, manually roll additional attack rolls for each extra beam, and apply the damage from the first cast to each successful hit of a beam.

### CODE REVIEW

**Comment by mlenser** [comment]
The beams all have a separate attack rolls and separate damage. This is accomplished by clicking the spell 1-4 times.

But you are correct that EB shouldn't have the scaling damage.

**Comment by mlenser** [comment]
Closing this as the dist file conflicts. In the future don't commit the dist files or I can't automatically merge. I'll fix it and push.

**Comment by alienth** [comment]
@mlenser  Sounds good. Thanks!

One note on separate damage. I do believe dmg should only be rolled once, based on PHB 196:

> If a spell or other effect deals damage to more than one target at the same time, roll the damage once for all of them.

Definitely a bit unclear in the case of Eldritch Blast, as it is a single spell which you making multiple attack rolls with.

**Comment by mlenser** [comment]
That is for AoE spells. Not for spells that have separate attack rolls.

See https://twitter.com/JeremyECrawford/status/611007135946686464

EB follows the same system as Scorching Ray.

**Comment by alienth** [comment]
Ah, good to know. Thanks for the link!

**Pull request closed without merging**
